# Generated by Django 4.1.6 on 2023-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "Worker", "verbose_name_plural": "Workers"},
        ),
        migrations.AddField(
            model_name="team",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="facebook_link",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Social Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Second name"),
        ),
    ]
