# Generated by Django 4.1.6 on 2023-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_team_options_team_telegram_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="photo",
            field=models.ImageField(null=True, upload_to="photo/%Y/%m/%d"),
        ),
    ]
