# Generated by Django 4.1.6 on 2023-02-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_main_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/cars/%Y/%m/%d/"
            ),
        ),
    ]
