# Generated by Django 4.1.6 on 2023-02-13 15:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_options_alter_car_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
