# Generated by Django 4.1.6 on 2023-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_carphoto_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_main_photo",
            field=models.ImageField(
                blank=True,
                default="photos/cars/defaultcar.jpg",
                null=True,
                upload_to="photos/cars/%Y/%m/%d/",
            ),
        ),
    ]
